export enum ArtistType {
  SINGER = "SINGER",
  LYRICIST = "LYRICIST",
  MUSIC_PRODUCER = "MUSIC_PRODUCER",
  MUSICPRODUCER = "MUSICPRODUCER",
  BAND = "BAND",
  COMPOSER = "COMPOSER",
  INSTRUMENTALIST = "INSTRUMENTALIST",
  RAPPER = "RAPPER",
  PRIMARY = "PRIMARY",
}
