export enum RailType {
  TRACKS = "TRACKS",
  GENRES = "GENRES",
  LANGUAGES = "LANGUAGES",
  MOODS = "MOODS",
  LABELS = "LABELS",
  PLAYLISTS = "PLAYLISTS",
}

export enum RailSourceType {
  MANUAL = "MANUAL",
  QUERY = "QUERY",
  AI_QUERY = "AI_QUERY",
}

export enum RailItemType {
  TRACK = "TRACK",
  GENRE = "GENRE",
  LANGUAGE = "LANGUAGE",
  MOOD = "MOOD",
  LABEL = "LABEL",
  PLAYLIST = "PLAYLIST",
}

export enum PageName {
  HOME = "HOME",
  CHARTBUSTERS = "CHARTBUSTERS",
  INTERNATIONAL = "INTERNATIONAL",
  REGIONAL_AND_INDIE = "REGIONAL_AND_INDIE",
  HOOPR_ORIGINALS = "HOOPR_ORIGINALS",
}
